export type BlogPost = {
  slug: string;
  title: string;
  description: string;
  category: string;
  readTime: string;
  date: string;
  accent: string;
  content: string[];
};

// Each `content` item is a paragraph. Headings are denoted with a `## ` prefix.
export const blogPosts: BlogPost[] = [
  {
    slug: "facebook-lead-follow-up-automation",
    title: "How to automate Facebook lead follow-ups without spamming",
    description:
      "Learn the compliant way to keep leads warm using messaging windows, tags, and smart automation.",
    category: "Guides",
    readTime: "6 min read",
    date: "2026-01-12",
    accent: "from-blue-500 to-indigo-600",
    content: [
      "Speed is everything when a lead messages your Facebook Page. Reply within minutes and you're far more likely to convert. Wait a few hours and the lead has usually moved on.",
      "The challenge is doing this at scale without breaking Meta's rules. In this guide we'll cover how to automate follow-ups in a way that keeps you compliant and your leads engaged.",
      "## Understand the 24-hour messaging window",
      "Meta allows businesses to message users freely for 24 hours after the user last interacted with you. After that window closes, you must use a Message Tag to send anything at all.",
      "PagePilot tracks this window automatically. When a lead messages you, the follow-up sequence only sends while you're still inside the allowed window.",
      "## Use tags instead of unsolicited broadcasts",
      "Outside the 24-hour window, the right approach is to reply using a permitted Message Tag. PagePilot respects these tags and never sends a message that Meta would block.",
      "## Set up a simple lead-warming sequence",
      "A good sequence looks like this: an instant acknowledgment, a helpful resource, then a gentle check-in. The goal is to keep the conversation moving, not to blast the user.",
      "With PagePilot you build this as a visual workflow, so you can see exactly what happens at each step.",
      "## The takeaway",
      "Automation works best when it feels human. Respect messaging windows, use tags correctly, and keep every message relevant.",
    ],
  },
  {
    slug: "facebook-page-metrics-that-matter",
    title: "5 Facebook Page metrics that actually predict revenue",
    description:
      "Stop chasing vanity metrics. These are the numbers that show which conversations drive sales.",
    category: "Analytics",
    readTime: "5 min read",
    date: "2026-01-05",
    accent: "from-indigo-500 to-purple-600",
    content: [
      "Most people track likes and reach. Those feel good, but they rarely predict whether your Facebook presence is actually making money.",
      "Here are the five metrics that matter most for a business page.",
      "## 1. First response time",
      "How quickly do you reply to a new message? Faster responses correlate strongly with higher conversion. PagePilot tracks this automatically.",
      "## 2. Lead capture rate",
      "Of the conversations you have, how many turn into a captured lead with contact details? This is the bridge between chatting and selling.",
      "## 3. Conversation-to-purchase rate",
      "This is the metric that ties everything together. How many conversations end in a sale?",
      "## 4. Follow-up completion rate",
      "Do your automated follow-ups actually send? If a sequence keeps failing, you're leaving revenue on the table.",
      "## 5. Cost per acquired customer",
      "Once you know your conversion flow, you can work backwards to understand what each customer actually costs you.",
      "## Use analytics to improve, not to admire",
      "The point of tracking these numbers is to find bottlenecks and fix them.",
    ],
  },
  {
    slug: "natural-language-ai-assistant-guide",
    title: "A practical intro to a natural-language AI assistant",
    description:
      "How an AI assistant that works in plain English drafts, summarizes, and acts on your behalf.",
    category: "AI",
    readTime: "7 min read",
    date: "2025-12-28",
    accent: "from-purple-500 to-fuchsia-600",
    content: [
      "AI assistants sound magical until you realize most of them require you to learn a specific syntax or prompt pattern. A truly useful assistant works the way you already talk.",
      "That's the core idea behind PagePilot's assistant: you describe what you want in plain English and it handles the rest.",
      "## Drafting replies that sound like you",
      "The assistant can read an incoming message and draft a reply. You review it, adjust it, and only then does it get sent.",
      "## Summarizing long threads",
      "Instead of reading a 40-message conversation, ask the assistant for a summary. It tells you who the user is, what they want, and what the next step should be.",
      "## Acting only after confirmation",
      "This is the part that matters most for trust. The assistant never sends a message externally without your explicit approval.",
      "## Start simple",
      "You don't need to automate everything on day one. Start with drafting and summaries, then let the assistant take on more as you get comfortable.",
    ],
  },
  {
    slug: "unified-inbox-benefits",
    title: "Why a unified inbox is the foundation of good support",
    description:
      "Managing multiple Facebook Pages from one place changes how fast and consistently you respond.",
    category: "Guides",
    readTime: "4 min read",
    date: "2025-12-20",
    accent: "from-emerald-500 to-teal-600",
    content: [
      "If you run more than one Facebook Page, you know the pain of switching between tabs, apps, and accounts just to keep up with messages.",
      "A unified inbox solves this by bringing every conversation into a single stream.",
      "## One place for everything",
      "No more logging in and out. Every message from every page appears in one inbox with the page name clearly labeled.",
      "## Assign and label conversations",
      "Route a message to the right teammate and tag it by topic. This keeps things organized as your team grows.",
      "## Real-time updates",
      "New messages, replies, and assignments update instantly, so nothing slips through the cracks.",
      "## Faster, more consistent replies",
      "When everything is in one place, response times drop and the quality of your replies goes up.",
    ],
  },
  {
    slug: "lead-crm-facebook-automation",
    title: "Turning Facebook chats into a real sales pipeline",
    description:
      "A conversation only becomes revenue when it enters a structured pipeline. Here's how to build one.",
    category: "Guides",
    readTime: "6 min read",
    date: "2025-12-12",
    accent: "from-sky-500 to-blue-600",
    content: [
      "A Facebook conversation is not a lead until you've captured it and moved it into a pipeline. Most businesses leave this step to chance.",
      "Here's a straightforward approach to turning chats into structured leads.",
      "## Capture the lead automatically",
      "When a message contains intent, capture the user's name, contact, and context into your CRM automatically.",
      "## Score your leads",
      "Not every conversation is equal. Score leads by intent so your team focuses on the ones most likely to convert.",
      "## Move leads through stages",
      "A simple pipeline — new, contacted, qualified, closed — gives you visibility into where each lead stands.",
      "## Follow up at the right time",
      "Use automation to send the right follow-up at the right moment, keeping the pipeline moving.",
    ],
  },
  {
    slug: "meta-policy-compliance-guide",
    title: "Staying compliant with Meta's messaging policies",
    description:
      "What every business should know about messaging windows, message types, and tags.",
    category: "Guides",
    readTime: "8 min read",
    date: "2025-11-30",
    accent: "from-blue-500 to-indigo-600",
    content: [
      "Meta's messaging rules exist to protect users from spam. If you ignore them, your page can be restricted or suspended.",
      "The good news is that compliance is straightforward once you understand the fundamentals.",
      "## The 24-hour messaging window",
      "After a user messages you, you have 24 hours to send messages freely. After that, you need a valid reason (a Message Tag) to reach out.",
      "## Message types and tags",
      "Tags allow you to send important, non-promotional messages like order updates or account notifications. They cannot be used for casual marketing.",
      "## What PagePilot does differently",
      "PagePilot is built to respect these rules. It checks eligibility before sending and tells you why a message can't be sent, rather than trying to bypass the restriction.",
      "## Play the long game",
      "Compliance isn't a constraint — it's how you build a sustainable, trustworthy presence.",
    ],
  },
  {
    slug: "visual-automation-workflows",
    title: "A beginner's guide to visual automation workflows",
    description:
      "Build trigger, condition, and action workflows visually — no code required.",
    category: "Guides",
    readTime: "5 min read",
    date: "2025-11-20",
    accent: "from-fuchsia-500 to-pink-600",
    content: [
      "Automation used to mean writing code or learning a complex tool. Visual workflows change that.",
      "With a visual builder, you connect blocks to describe what should happen automatically.",
      "## Triggers, conditions, and actions",
      "Every workflow has three parts. A trigger starts it, a condition decides if it should run, and an action does the work.",
      "## Automating common replies",
      "A simple workflow can automatically tag incoming messages by keyword, or send a friendly acknowledgment to new leads.",
      "## Following up without lifting a finger",
      "Set a workflow to send a follow-up message if a lead hasn't replied within a day.",
      "## Keep it visible",
      "Because it's visual, your whole team can understand what's automated — no guessing involved.",
    ],
  },
  {
    slug: "response-time-impact-on-sales",
    title: "How response time directly impacts your sales",
    description:
      "The data is clear: faster responses mean more conversions. Here's why speed matters so much.",
    category: "Analytics",
    readTime: "4 min read",
    date: "2025-11-10",
    accent: "from-emerald-500 to-teal-600",
    content: [
      "When a potential customer messages your page, they're usually ready to act now — not in an hour.",
      "Response time is one of the strongest predictors of whether a conversation becomes a sale.",
      "## The first response is the most important",
      "Replying within minutes, rather than hours, dramatically increases your chances of keeping the lead engaged.",
      "## Automation buys you time",
      "Even an automated acknowledgment tells the customer you're listening, which keeps them from going to a competitor.",
      "## Measure it, then improve it",
      "PagePilot tracks your response times so you can see exactly where the delays are happening.",
    ],
  },
  {
    slug: "facebook-ai-chatbot-vs-assistant",
    title: "Chatbot vs AI assistant: what's the difference?",
    description:
      "Not all AI is the same. Here's how a true assistant differs from a basic chatbot.",
    category: "AI",
    readTime: "6 min read",
    date: "2025-10-28",
    accent: "from-pink-500 to-rose-600",
    content: [
      "Chatbot and AI assistant are often used interchangeably, but they describe very different experiences.",
      "Understanding the difference helps you choose the right tool for your business.",
      "## Chatbots follow scripts",
      "A chatbot responds to specific keywords with pre-written messages. It breaks down the moment a conversation goes off-script.",
      "## AI assistants understand intent",
      "An assistant reads the meaning behind a message and responds contextually, even when the wording is unexpected.",
      "## Assistants work with you, not instead of you",
      "The most powerful assistants draft, summarize, and suggest — then let you confirm before acting. You stay in control.",
      "## Choose the right level of automation",
      "Start with drafting and summaries, then expand as you build trust in the system.",
    ],
  },
  {
    slug: "multi-page-facebook-management",
    title: "Managing multiple Facebook Pages without the chaos",
    description:
      "Agencies and multi-brand teams need a better way to handle many pages at once.",
    category: "Guides",
    readTime: "5 min read",
    date: "2025-10-15",
    accent: "from-amber-500 to-orange-600",
    content: [
      "Agencies managing multiple client pages face a unique challenge: staying organized across many accounts at once.",
      "The right tooling turns this from chaos into a repeatable process.",
      "## Switch between pages instantly",
      "Instead of logging in and out of accounts, switch between all your pages from a single dashboard.",
      "## Keep teams aligned",
      "Assign conversations to specific teammates and set roles so everyone knows their responsibilities.",
      "## Consistent quality across clients",
      "Shared automation and templates ensure every client gets the same high standard of response.",
      "## Scale without adding headcount",
      "Automation handles the repetitive work, so your team can focus on the conversations that need a human touch.",
    ],
  },
  {
    slug: "facebook-automation-tools-comparison",
    title: "How to choose the right Facebook automation tool",
    description:
      "A framework for evaluating automation platforms based on your actual needs.",
    category: "Guides",
    readTime: "7 min read",
    date: "2025-09-30",
    accent: "from-indigo-500 to-purple-600",
    content: [
      "There are dozens of tools that promise to automate your Facebook messaging. Most are either too limited or too complex.",
      "Here's a simple framework for choosing the right one.",
      "## 1. Does it respect Meta's policies?",
      "If a tool promises to bypass restrictions, run away. That's a fast track to getting your page suspended.",
      "## 2. Does it unify everything?",
      "Your inbox, leads, campaigns, and automations should live in one place, not across five different tools.",
      "## 3. Is the automation visual?",
      "If you can't see what's automated, you can't trust it. Visual workflows make automation understandable.",
      "## 4. Does the AI ask before acting?",
      "A good AI assistant drafts and suggests, but always gives you the final say on external actions.",
      "## 5. Can your team collaborate?",
      "Roles, assignments, and real-time updates matter as soon as more than one person is involved.",
    ],
  },
  {
    slug: "grow-facebook-page-seo",
    title: "SEO tips for your Facebook Page in 2026",
    description:
      "How to make your page easier to find, both on Facebook and on Google.",
    category: "Guides",
    readTime: "5 min read",
    date: "2025-09-18",
    accent: "from-sky-500 to-blue-600",
    content: [
      "Facebook Pages don't just rank on Facebook — they show up in Google search results too. A few small optimizations go a long way.",
      "## Complete your page details",
      "A clear name, category, and description help both Facebook and Google understand what you do.",
      "## Use keywords naturally",
      "Include the terms your customers actually search for in your description and about section — without stuffing.",
      "## Post consistently",
      "Fresh, relevant content signals that your page is active and worth surfacing.",
      "## Respond to reviews and messages",
      "Engagement and responsiveness are signals that improve your page's standing.",
      "## Track what's working",
      "Use analytics to see which posts and conversations drive the most traffic and leads.",
    ],
  },
];
